version: 1
disable_existing_loggers: True
formatters:
  default:
    format: '%(asctime)s %(levelname)-9s %(message)s'
handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
loggers:
  root:
    level: INFO
    handlers:
      - default
